version: '3.9'

services:
  supabase-db:
    container_name: supabase-db
    image: supabase/postgres
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - supadb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  supabase-auth:
    image: supabase/gotrue
    ports:
      - "${AUTH_PORT:-9999}:9999"
    environment:
      GOTRUE_DB_DRIVER: postgres
      DB_DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@supabase-db:5432/${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      SITE_URL: ${SITE_URL}
      API_EXTERNAL_URL: ${AUTH_API_URL}

  backend:
    build: ./backend
    depends_on:
      - supabase-db
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@supabase-db:5432/${DB_NAME}
      SUPABASE_URL: http://supabase-auth:9999
      SUPABASE_KEY: ${JWT_SECRET}
    ports:
      - "${BACKEND_PORT:-3000}:3000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:${BACKEND_PORT:-3000}
    ports:
      - "${FRONTEND_PORT:-4200}:80"

volumes:
  supadb-data:
