version: '3.9'
services:
  supabase:
    container_name: supabase
    build: ./supabase
    volumes:
      - supadb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      - "8000:8000"
      - "54323:54323"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@supabase:5432/access_control
      SUPABASE_URL: http://supabase:8000
      SUPABASE_KEY: ${SUPABASE_SERVICE_KEY}
    depends_on:
      - supabase
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    environment:
      VITE_API_URL: http://localhost:3000
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  supadb-data:
