name: Test Database Schema

on:
  push:
    paths:
      - 'db/**'
      - '.github/workflows/db.yml'
      - 'docker-compose.yml'
  pull_request:
    paths:
      - 'db/**'
      - '.github/workflows/db.yml'
      - 'docker-compose.yml'

jobs:
  test-db:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: access_control
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PGPASSWORD: postgres

    steps:
      - uses: actions/checkout@v4

      - name: Esperar a que PostgreSQL esté listo
        run: |
          for i in {1..20}; do
            if pg_isready -h localhost -p 5432 -U postgres; then
              break
            fi
            sleep 3
          done

      - name: Cargar entidades y datos iniciales(seed)
        run: |
          psql -h localhost -U postgres -d access_control -f db/entidades.sql
          psql -h localhost -U postgres -d access_control -f db/seed.sql
