name: Verificar Configuración Local de Supabase

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/**'
      - '.github/workflows/test_setup.yml'
  pull_request:
    paths:
      - 'supabase/**'
      - '.github/workflows/test_setup.yml'

jobs:
  test-local-db-setup:
    name: Test de Migraciones y Seed Locales
    runs-on: ubuntu-latest

    env:
      ADMIN_EMAIL: 'test-admin@example.com'
      ADMIN_PASSWORD: 'password123'
      USER_EMAIL: 'test-user@example.com'
      USER_PASSWORD: 'password123'
      SUPABASE_NON_INTERACTIVE: true
      DATABASE_URL: 'postgresql://postgres:postgres@localhost:54322/postgres'

    steps:
      - name: 1. Clonar el repositorio
        uses: actions/checkout@v4

      - name: 2. Instalar la CLI de Supabase
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: 3. Levantar el entorno local de Supabase
        run: supabase start

      - name: 4. Aplicar migraciones (sin ejecutar el seed)
        run: supabase db reset --no-seed

      - name: 5. Esperar a que PostgreSQL esté listo para aceptar conexiones
        run: |
          for i in {1..10}; do
            pg_isready -d "$DATABASE_URL" -q && break
            echo "Esperando a la base de datos... ($i/10)"
            sleep 1
          done

      - name: 6. Ejecutar SEED con variables de entorno
        run: envsubst < supabase/seed.sql | psql "$DATABASE_URL"

      - name: 7. Detener el entorno local de Supabase
        if: always()
        run: supabase stop
