name: Verificar Docker Compose Funciona

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  docker-compose-test:
    name: Validar docker-compose up --build
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar variables de entorno requeridas
        run: |
          echo "SUPABASE_URL=http://localhost:54321" >> .env
          echo "SUPABASE_KEY=clave-de-prueba" >> .env
          echo "SUPABASE_ANON_KEY=anon-key-de-prueba" >> .env
          echo "SUPABASE_SERVICE_KEY=service-key-de-prueba" >> .env

      - name: Instalar Docker Compose v2
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Ejecutar docker-compose up --build (verificación)
        run: |
          docker-compose up --build -d
          sleep 15  # da tiempo a los servicios para arrancar
          docker-compose ps

      - name: Verificar estado de los contenedores
        run: |
          docker-compose ps | grep "Exit" && exit 1 || echo "Todos los servicios están funcionando."

      - name: Apagar servicios
        if: always()
        run: docker-compose down
