name: Validar Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-docker-compose:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      VITE_API_URL: ${{ secrets.VITE_API_URL }}

    steps:
      - name: 1. Clonar repositorio
        uses: actions/checkout@v4

      - name: 2. Crear archivo .env con secretos
        run: |
          echo "SUPABASE_URL=${SUPABASE_URL}" >> .env
          echo "SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}" >> .env
          echo "DATABASE_URL=${DATABASE_URL}" >> .env
          echo "VITE_API_URL=${VITE_API_URL}" >> .env

      - name: 3. Instalar Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: 4. Levantar servicios
        run: |
          docker-compose --env-file .env up --build -d
          sleep 30  # espera para que todos los servicios arranquen
          docker-compose ps

      - name: 5. Verificar que todos los contenedores estén UP
        run: |
          STATUS=$(docker inspect --format='{{.State.Status}}' $(docker ps -aq))
          echo "$STATUS" | grep -qv "exited" || (echo "Un servicio falló al levantar" && exit 1)

      - name: 6. Detener y limpiar contenedores
        if: always()
        run: docker-compose down -v
